version: "3"

tasks:
  migration:
    cmds:
      - psql -h localhost -p 5432 -U postgres test < .\pkg\model\Init_model.sql
    silent: true
  proto:
    cmds:
      - protoc --proto_path=. --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative pkg/protobuf/user/user.proto
    silent: true
  client:
    cmds:
      - grpcui -port 8090 -plaintext localhost:50051
    silent: true
  server:
    cmds:
      - LOCAL=1 go run cmd/server/server.go
    silent: true
  build:
    cmds:
      - GOOS=linux go build -ldflags="-s -w" -o main cmd/server/server.go
    silent: true
